---
permalink: pretty
destination: public
exclude:
  - RedHotVengeance.sublime-project
  - RedHotVengeance.sublime-workspace
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - app.rb
  - public
paginate: 2