---
safe: true
lsi: false
name: Red Hot Vengeance
description: Words and word-shaped creations, furiously formed by Ian Lollar.
url: http://redhotvengeance.com
permalink: pretty
destination: public
exclude:
  - public
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
excerpt_separator: <!--more-->
paginate: 10
paginate_path: "page/:num"
markdown: redcarpet
pygments: true
redcarpet:
  extensions: [autolink, no_intra_emphasis, strikethrough, superscript, tables]
